# Generated by Django 2.0.3 on 2018-03-28 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('script', models.CharField(max_length=50, unique=True, verbose_name='Script')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('Availability Failure', 'Availability Failure'), ('Performance Failure', 'Performance Failure')], max_length=50, verbose_name='Alarm Type')),
                ('connect_time', models.IntegerField(blank=True, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_availability_test_passed', models.BooleanField(verbose_name='Is Availability Test Passed?')),
                ('is_performance_test_passed', models.IntegerField(default='-2', verbose_name='Is Performance Test Passed?')),
                ('connect_time', models.IntegerField(blank=True, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('uri', models.CharField(max_length=1000, verbose_name='URI')),
                ('port', models.IntegerField(blank=True, help_text='Needed only for Ping and Postgresql agents', null=True, verbose_name='Port')),
                ('protocol', models.CharField(choices=[('N/A', 'N/A'), ('TCP', 'TCP'), ('UDP', 'UDP')], default='N/A', max_length=20, verbose_name='Protocol')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Password')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_availability_checked', models.BooleanField(default=True, verbose_name='Is Availability Checked?')),
                ('is_performance_checked', models.BooleanField(default=True, verbose_name='Is Performance Checked?')),
                ('performance_threshold', models.IntegerField(blank=True, default=2000, null=True, verbose_name='Performance Threshold in MS')),
                ('is_alarm_created_for_availability', models.BooleanField(default=True, verbose_name='Is Alarm Created for Availability Failure?')),
                ('is_alarm_created_for_performance', models.BooleanField(default=True, verbose_name='Is Alarm Created for Performance Failure?')),
                ('is_data_stored_for_availability', models.BooleanField(default=True, verbose_name='Is Data Stored for Availability?')),
                ('is_data_stored_for_performance', models.BooleanField(default=True, verbose_name='Is Data Stored for Performance?')),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.Agent')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.Profile'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('agent', 'name')},
        ),
    ]
