# Generated by Django 2.0.3 on 2018-03-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='port',
        ),
    ]
