# Generated by Django 2.0.3 on 2018-03-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_profile_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uri',
            field=models.CharField(help_text='Ex: localhost:22 or localhost:5432/mydb', max_length=1000, verbose_name='URI'),
        ),
    ]
